In [2]:
import pandas as pd
import json

In [4]:
with open("runtime_gpt-o4-mini.json") as f:
    data = json.load(f)

In [5]:
df = pd.DataFrame(data)
df["total"] = df["draft"] + df['exec'] + df["parse"]

In [11]:
df.describe()

           draft       exec      parse      total
count  10.000000  10.000000  10.000000  10.000000
mean   20.186122   9.932300   3.293831  33.412254
std     6.571313   9.420871   1.293402  10.408426
min    12.627592   2.185056   1.762493  18.920010
25%    14.130142   2.717874   2.579669  24.770646
50%    18.716848   4.488760   2.971642  34.184194
75%    26.544661  19.849744   3.867122  40.445175
max    29.608970  23.323659   6.228523  50.934810

In [10]:
agg = df.sum().to_frame('sum')
agg['percent_of_total'] = agg['sum'] / agg.loc['total', 'sum'] * 100
agg

              sum  percent_of_total
draft  201.861223         60.415327
exec    99.323003         29.726520
parse   32.938311          9.858153
total  334.122537        100.000000

In [15]:
with open("logs/2-wakeful-glaring-lemur/journal.json") as f:
    journal = json.load(f)

In [19]:
nodes = journal['nodes']
df_nodes = pd.DataFrame(nodes)

In [21]:
df_nodes["is_buggy"].sum()

3