In [1]:
import pandas as pd
import json

In [2]:
with open("runtime_gpt-o4-mini.json") as f:
    data = json.load(f)

In [3]:
df = pd.DataFrame(data)
df["total"] = df["draft"] + df['exec'] + df["parse"]

In [4]:
df.describe()

           draft        exec      parse       total
count  50.000000   50.000000  50.000000   50.000000
mean   26.561675   37.099578   2.824144   66.485397
std     7.209950   40.707294   0.947632   43.229734
min    14.454395    0.586779   1.843982   19.481865
25%    21.208888   14.771333   2.360495   36.315913
50%    25.730191   16.491411   2.697612   51.407158
75%    32.610417   56.427674   2.906461   92.509086
max    40.174450  187.535073   7.901383  219.157363

In [5]:
agg = df.sum().to_frame('sum')
agg['percent_of_total'] = agg['sum'] / agg.loc['total', 'sum'] * 100
agg

               sum  percent_of_total
draft  1328.083727         39.951141
exec   1854.978921         55.801094
parse   141.207183          4.247765
total  3324.269831        100.000000

In [15]:
with open("logs/2-wakeful-glaring-lemur/journal.json") as f:
    journal = json.load(f)

In [19]:
nodes = journal['nodes']
df_nodes = pd.DataFrame(nodes)

In [21]:
df_nodes["is_buggy"].sum()

3

In [ ]:
d