In [4]:
import json
import os
import pandas as pd

In [5]:
BASE_LOG_FOLDER = "2-merry-onyx-lemming"

In [6]:
with open(f"{BASE_LOG_FOLDER}/journal.json") as f:
    selected_logs = json.load(f)

In [7]:
logs_df = pd.DataFrame(selected_logs["nodes"])

In [8]:
logs_df[["is_buggy","metric","exec_time"]]

   is_buggy                                 metric  exec_time
0      True      {'value': None, 'maximize': None}  27.512935
1     False  {'value': 0.17234, 'maximize': False}   0.699610
2      True      {'value': None, 'maximize': None}   0.838175
3      True      {'value': None, 'maximize': None}  42.748316

In [9]:
logs_df.columns

Index(['code', 'plan', 'step', 'id', 'ctime', 'parent', 'children',
       '_term_out', 'exec_time', 'exc_type', 'exc_info', 'exc_stack',
       'analysis', 'metric', 'is_buggy'],
      dtype='object')

In [10]:
buggy = (logs_df["is_buggy"] == True).sum() / len(logs_df)
print("{}%".format(round(buggy * 100, 2)))

75.0%

In [11]:
logs_df["metric"].apply(lambda x: x["maximize"]).describe()

count         1
unique        1
top       False
freq          1
Name: metric, dtype: object

In [12]:
logs_df["metric"] = logs_df["metric"].apply(lambda x: x["value"])

In [13]:
pipelines_ordered_by_eval = logs_df.sort_values(by="metric", ascending=True)

In [14]:
pipelines_ordered_by_eval.head(3)

,code,plan,step,id,ctime,parent,children,_term_out,exec_time,exc_type,exc_info,exc_stack,analysis,metric,is_buggy
1,import pandas as pd\nimport numpy as np\nfrom ...,We train two independent LightGBM classifiers ...,1,1cf36f16882f4909a0420dd67a134495,1.763055e+09,None,[],[Execution time: a moment seconds (time limit ...,0.699610,None,None,None,The training script successfully executed with...,0.17234,False
0,import os\nimport pandas as pd\nimport numpy a...,I propose concatenating the provided train CSV...,0,4e6fa44157104f62bb61b12eda134d4c,1.763054e+09,None,[],"[Traceback (most recent call last):\n File ""r...",27.512935,ValueError,{'args': ['could not convert string to float: ...,[[/home/elias/skrub-exps/aideml/aide/interpret...,The code fails at the step where it tries to c...,NaN,True
2,import pandas as pd\nimport numpy as np\nfrom ...,We will train two independent XGBoost classifi...,2,9e55f57e665447709668082526af19b9,1.763055e+09,None,[],"[Traceback (most recent call last):\n File ""r...",0.838175,ModuleNotFoundError,"{'args': ['No module named 'xgboost''], 'name'...",[[/home/elias/skrub-exps/aideml/aide/interpret...,The script failed to execute because the 'xgbo...,NaN,True

In [15]:
for i,code in enumerate(logs_df["code"]):
    os.makedirs(f"{BASE_LOG_FOLDER}/pipelines", exist_ok=True)
    with open(f"{BASE_LOG_FOLDER}/pipelines/pipeline{i}.py", "w") as f:
        f.write(code)

In [16]:
logs_df["is_buggy"]

0     True
1    False
2     True
3     True
Name: is_buggy, dtype: bool

In [17]:
logs_df.head(5)["exec_time"].sum()

71.79903554916382